function [ddx,ddq] = autoGen_cartPoleDynamics(q,dq,u,m1,m2,g,l)
%autoGen_cartPoleDynamics
%    [DDX,DDQ] = autoGen_cartPoleDynamics(Q,DQ,U,M1,M2,G,L)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Nov-2022 16:32:03

t2 = cos(q);
t3 = sin(q);
t4 = dq.^2;
t5 = t2.^2;
t6 = m2.*t5;
t7 = -t6;
t8 = m1+m2+t7;
t9 = 1.0./t8;
ddx = t9.*(u+g.*m2.*t2.*t3+l.*m2.*t3.*t4);
if nargout > 1
    ddq = -(t9.*(t2.*u+g.*m1.*t3+g.*m2.*t3+l.*m2.*t2.*t3.*t4))./l;
end
