csv_d_path="C:\Users\hayashide\Desktop\kazu_ws\sotsuron_experiment\sotsuron_experiment\question\answer_d.csv"
data_d=readmatrix(csv_d_path)
csv_L_path="C:\Users\hayashide\Desktop\kazu_ws\sotsuron_experiment\sotsuron_experiment\question\answer_L.csv"
data_L=readmatrix(csv_L_path);

q=[
    "1-1 偽物のような⇔自然な",...
    "1-2 機械的⇔人間的",...
    "1-3 意識を持たない⇔意識を持っている",...
    "1-4 人工的⇔生物的",...
    "1-5 ぎこちない動き⇔洗練された動き",...
    "2-1 死んでいる⇔生きている",...
    "2-2 活気のない⇔生き生きとした",...
    "2-3 機械的な⇔有機的な",...
    "2-4 人工的な⇔生物的な",...
    "2-5 不活発な⇔対話的な",...
    "2-6 無関心な⇔反応のある",...
    "3-1 嫌い⇔好き",...
    "3-2 親しみにくい⇔親しみやすい",...
    "3-3 不親切な⇔親切な",...
    "3-4 不愉快な⇔愉快な",...
    "3-5 ひどい⇔良い",...
    "4-1 無能な⇔有能な",...
    "4-2 無知な⇔物知りな",...
    "4-3 無責任な⇔責任のある",...
    "4-4 知的でない⇔知的な",...
    "4-5 愚かな⇔賢明な",...
    "5-1 不安な⇔落ち着いた",...
    "5-2 動揺している⇔冷静な",...
    "5-3 平穏な⇔驚いた",...
    ];

for n_col=3:length(data_d(1,:))-2
    fig=figure(1);clf;
    A=data_d(2:end,[n_col]);
    C=categorical(A,[1 2 3 4 5],{'1','2','3','4','5'});
    AL=data_L(2:end,[n_col]);
    CL=categorical(AL,[1 2 3 4 5],{'1','2','3','4','5'});
    histogram(C,'BarWidth',0.5);
    hold on
    histogram(CL,'BarWidth',0.5);
    legend("RGB-D","LRF")
    ylim([0,15])
    title(q(n_col-2));
    saveas(fig,"C:\Users\hayashide\Desktop\kazu_ws\sotsuron_experiment\sotsuron_experiment\question\hist_q"+string(n_col)+".png");
end