function f = autoGen_f(omg,th,v)
%autoGen_f
%    F = autoGen_f(OMG,TH,V)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    01-Nov-2022 16:19:25

f = [v.*cos(th);v.*sin(th);omg];
