function [t_interp,z_interp,z10_interp,u_interp]=linear_interp(t,z,z10,u)
    n=length(t)
    t_interp=linspace(t(1),t(end),15*(n-1)+1);
    z_interp=[interp1(t,z(1,:),t_interp);...
    interp1(t,z(2,:),t_interp);...
    interp1(t,z(3,:),t_interp);...
    interp1(t,z(4,:),t_interp);...
    interp1(t,z(5,:),t_interp);...
    interp1(t,z(6,:),t_interp);...
    interp1(t,z(7,:),t_interp);...
    interp1(t,z(8,:),t_interp)];

    z10_interp=[interp1(t,z10(1,:),t_interp);...
    interp1(t,z10(2,:),t_interp);...
    interp1(t,z10(3,:),t_interp);...
    interp1(t,z10(4,:),t_interp);...
    interp1(t,z10(5,:),t_interp);...
    interp1(t,z10(6,:),t_interp);...
    interp1(t,z10(7,:),t_interp);...
    interp1(t,z10(8,:),t_interp);...
    interp1(t,z10(9,:),t_interp);...
    interp1(t,z10(10,:),t_interp)];


    u_interp=[interp1(t,u(1,:),t_interp);...
    interp1(t,u(2,:),t_interp);...
    interp1(t,u(3,:),t_interp);...
    interp1(t,u(4,:),t_interp)];
end